add check for urbackupclientctl

diff --git a/check_urbackupclient b/check_urbackupclient
--- a/check_urbackupclient
+++ b/check_urbackupclient
@@ -1,22 +1,31 @@
 #!/bin/bash
-#
-# by Oliver Katte @2018
-#
-#########################
 
 function get_backuptime {
+	_bin=`which urbackupclientctl`
+	if [ -z "$_bin" ]; then
+                echo "NO Client installed"
+                exit 1
+        fi
         _timestamp=`urbackupclientctl status | grep last_backup_time | cut -d" " -f2 | sed -e "s/,//g"`
         _backuptime=$(date -d @$_timestamp +%H\:%M\:%S\ %d.%m.%Y)
 	_day=$(date -d @$_timestamp +%d.%m.%Y)
 	_date=$(date +%d.%m.%Y)
 	if [ "$_day" == "$_date" ]; then
 		echo "OK - Last backup $_backuptime"
+		exit 0
 	else
 	        echo "CRITICAL - Please check backups $_backuptime"
+		exit 2
 	fi
         }
 
 function get_backupstatus {
+	unset $_bin
+	_bin=`which urbackupclientctl`
+        if [ -z "$_bin" ]; then
+                echo "NO Client installed"
+                exit 1
+        fi
         _get_status=`urbackupclientctl status | grep failed | cut -d":" -f1 | sed -e 's/\"//g'`
         if [ -z "$_get_status" ]; then
 		echo "OK - Backup is fine"
@@ -35,6 +44,13 @@ function help {
 	echo "$0 -b/-s"
 	}
 	
+
+#echo "Get backuptime: " && get_backuptime
+#
+#echo "##################################"
+#
+#echo "Get status of backups: " && get_backupstatus
+
 while getopts "bsh" opt; do
    case $opt in
 	b)
@@ -42,6 +58,9 @@ while getopts "bsh" opt; do
 	;;
 	s)
 	get_backupstatus
+	;;
+	\?)
+	echo "Invalid option: -$OPTARG" >&2
 	;;
 	h)
 	help
